apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: gestion-notes
type: Opaque
data:
  DB_PASSWORD: cm9vdHBhc3N3b3Jk  # base64 de "rootpassword"
  APP_KEY: YmFzZTY0OmMvVS81aXJ0QmIrSVA4TWZHdCtlQXlScnJJcGcvV3hpVi9nSENCeVVPR3M9  # base64 de la clé Laravel