apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: gestion-notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "gestion_notes"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: gestion-notes
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: gestion-notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: php:8.2-apache
        ports:
        - containerPort: 80
        command: ["/bin/sh"]
        args: ["-c", "echo '<h1>Backend API</h1>' > /var/www/html/index.html && apache2-foreground"]
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: gestion-notes
spec:
  selector:
    app: backend
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: gestion-notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        command: ["/bin/sh"]
        args: ["-c", "echo '<h1>Gestion Notes</h1><p>Application DevOps</p>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: gestion-notes
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    nodePort: 30080
  type: NodePort