apiVersion: v1
kind: Namespace
metadata:
  name: gestion-notes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: gestion-notes
data:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "gestion_notes"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  APP_KEY: "base64:c/U/5irtBb+IP8MfGt+eAyRrrIpg/WxiV/gHCByUOGs="
  APP_ENV: "production"
  APP_DEBUG: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: gestion-notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "gestion_notes"
        ports:
        - containerPort: 3306
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: gestion-notes
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: gestion-notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z mysql 3306; do sleep 2; done']
      containers:
      - name: backend
        image: appnotes-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend-config
        command: ["/bin/sh"]
        args:
        - -c
        - |
          sleep 20
          php artisan migrate:fresh --seed --force
          php artisan serve --host=0.0.0.0 --port=8000
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: gestion-notes
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: gestion-notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: appnotes-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: gestion-notes
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080