version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_notes
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: php:8.2-apache
    ports:
      - "8000:80"
    volumes:
      - ./appNotes:/var/www/html
    environment:
      DB_HOST: db
      DB_DATABASE: gestion_notes
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        apt-get update && apt-get install -y default-mysql-client &&
        docker-php-ext-install pdo pdo_mysql &&
        a2enmod rewrite &&
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
        cd /var/www/html &&
        composer install --no-dev &&
        sleep 10 &&
        php artisan migrate:fresh --seed --force &&
        apache2-foreground
      "

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin

volumes:
  db_data:
